### PR TITLE
Version 3.2.0

### PR DESCRIPTION
**Pull request by jperera**
PR for 3.2.0 version

### CODE REVIEW

**Comment by vicsufer** [comment]
Could you update this value with the new version? https://github.com/idealista/prom2teams/blob/master/helm/Chart.yaml#L2

Related issue: https://github.com/idealista/prom2teams/issues/236

**Comment by vicsufer** [comment]
Also [setup.py](https://github.com/idealista/prom2teams/blob/develop/setup.py#L13) need to be updated with the new version to deploy changes to pip.

**Comment by jperera** [comment]
> Could you update this value with the new version? https://github.com/idealista/prom2teams/blob/master/helm/Chart.yaml#L2
> 
> Related issue: #236

Done

**Comment by jperera** [comment]
> Also [setup.py](https://github.com/idealista/prom2teams/blob/develop/setup.py#L13) need to be updated with the new version to deploy changes to pip.

Done

**Review by blalop — APPROVED** [review]

**Review by vicsufer — APPROVED** [review]

**Pull request merged**
