### PR TITLE
feat: Migrate to Teams Workflow

### LINKED ISSUE #350: [BUG] Change Office365 Webhook to Teams Workflow
### Description

Microsoft recently added the following message when using the Office365 Connector. "Action Required:
O365 connectors within Teams will be deprecated and notifications from this service will stop.
Learn more 
about the timing and how the Workflows app provides a more flexible and secure experience. If you want to continue receiving these types of messages, you can use a workflow to post messages from a webhook request.
Set up workflow".

When following the recommended steps we started receiving the following error when trying to execute the post "configparser.InterpolationSyntaxError: '%' must be followed by '%' or '(', found: '%2Fmanual%%2Frun&sv=1.0&sig=mXASDASsaPihsdaARjeknv' "

Apparently there is an error in the webhook url that contains '%'

### Steps to Reproduce

1. Create Teams Power Automate Workflow and Select Webhook flow
2. Copy Webhook Url and Update or Install Helm chart with Webhook Url's 
3. Send a Post request

**Expected behavior:**
Send message to Teams Channel

**Actual behavior:**
Error above

File "/usr/local/lib/python3.8/configparser.py", line 395, in before_get
2024-07-10T10:13:16.777425044-03:00     self._interpolate_some(parser, option, L, value, section, defaults, 1)
2024-07-10T10:13:16.777428260-03:00   File "/usr/local/lib/python3.8/configparser.py", line 442, in _interpolate_some
2024-07-10T10:13:16.777431522-03:00     raise InterpolationSyntaxError(
2024-07-10T10:13:16.777434864-03:00 configparser.InterpolationSyntaxError: '%' must be followed by '%' or '(', found:

**Reproduces how often:** 
100% of time

### Environment

- The release version/s you are using: 
- Kubernetes 1.27
- Container image: idealista/prom2teams:4.2.0

### PR DESCRIPTION
**Pull request by FrankBlooBM**
### Description of the Change
This PR introduces support for the new required Teams Workflow. The new webhooks need to be registered via Teams (Apps) -> Workflows -> Post to a channel when a webhook request is received. 

Main changes:
- Move from legacy `MessageCard` to `AdaptiveCards`
- Teams Workflow webhook responds with an HTTP 202 instead of 200, and does not include a body

### Benefits

- Support the Teams Workflow
- Exiting Teams Webhooks (going to the office endpoints) also support the new `AdaptiveCards` structure

### Possible Drawbacks
 
- Default template is change

### Applicable Issues

Closes https://github.com/idealista/prom2teams/issues/350

Feedback on this one is much appreciated!

### CODE REVIEW

**Comment by xtianae7** [comment]
Hello,
first of all, thank you very much for contributing, we will be reviewing the PR :) .

Could you also update the changelog?

**Comment by FrankBlooBM** [comment]
Changelog is updated :) Seems that SonarCloud job fails due to a token issue?

**Review by emepege — APPROVED** [review]

**Comment by xtianae7** [comment]
Hello, SonarCloud doesn't work with external PRs, thats the reason why it is failing. Don't worry :)

**Review by YaraGomezSaiz — APPROVED** [review]
LGTM

**Review by xtianae7 — APPROVED** [review]

**Review by santi-eidu — APPROVED** [review]

**Comment by angelosnm** [comment]
I'm stilling getting the error below when using the workflow webhook URL

````
configparser.InterpolationSyntaxError: '%' must be followed by '%' or '(', found: '%2Ftriggers%2Fmanual%2Frun&sv=1.0&sig=BJuk7SIUpaHgjlq1eb9zRsXE7XADWmRlGy2_BzrzH1g'
[pid: 11|app: 0|req: 11/11] 172.25.0.2 () {26 vars in 325 bytes} [Wed Oct  9 11:22:07 2024] POST /v2/connector => generated 126 bytes in 13 msecs (HTTP/1.1 500) 2 headers in 99 bytes (1 switches on core 0)
````

**Pull request merged**
