### PR TITLE
Multiple connectors

### LINKED ISSUE #170: Helm chart connectors
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Checked that your issue isn't already filled: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aidealista
    * Checked that there is not already provided the described functionality

### Description
Can't see from the README how to add additional connectors on the helm config. 

Also, thank you for making this. It's great!

### Versions
Helm Chart
### Additional Information

Deployed this on Kubernetes/rancher, and getting my alerts through to teams.

### PR DESCRIPTION
**Pull request by krmichel**
### Description of the Change

I would like to be able to specify multiple connectors with out having to create my own ini file and configmap out side of the chart.  I have added the ability to do that with the chart by adding a map to the values that can contain multiple connector name and urls.

### Benefits

Being able to install the helm chart and specify multiple connectors without breaking backwards compatibility.  I also added validation to make sure the log level provided is a valid value.  I also changed the deployment to use the chart's appVersion as the default image tag if one isn't provided.

### Possible Drawbacks

If someone was supplying an invalid log level before and it didn't cause a crash loop they would no longer be able to use their same values and have a successful installation

### Applicable Issues

fixes #170

### CODE REVIEW

**Comment by krmichel** [comment]
@dortegau not sure who to contact to see about having the PR reviewed.  Can you provide suggestions?

**Comment by krmichel** [comment]
@manuhortet @jmonterrubio @frantsao do any of you know who would be appropriate to ask to look at this PR?

**Comment by frantsao** [comment]
> @manuhortet @jmonterrubio @frantsao do any of you know who would be appropriate to ask to look at this PR?

Hello, I added some of my mates in order to review the PR. I hope we'll do it soon.

**Comment by krmichel** [comment]
@frantsao @jmonterrubio  and @jperera have any of you had a chance to look at this PR?

**Comment by krmichel** [comment]
@frantsao @jmonterrubio and @jperera this is over 3 months old any chance it can get looked at?

**Comment by frantsao** [comment]
> @frantsao @jmonterrubio and @jperera this is over 3 months old any chance it can get looked at?

Hello, @krmichel,
Shame on us. We had some messes. We'll try to do a review before thursday.
Thanks again for your contribution.

**Review by frantsao — APPROVED** [review]

**Review by vicsufer — APPROVED** [review]

**Review by jperera — APPROVED** [review]

**Comment by krmichel** [comment]
Sorry, just noticed the change log had a conflict

**Pull request merged**
